          SUBROUTINE M2IMPLICIT(Y,T0,H)
        COMMON /MYVAR/ A,B,C,E,TAUR,TWOMU,XMHIGH1,XMHIGH2
         COMMON /MYVAR1/ GDOTR(2),TAU(2)
            DIMENSION X(2),WK(36),PAR(3),Y(2)
         EXTERNAL FCN
C ITERATION SCHEME FOR BACKWARD EULER APPROXMIATION
C OF AN INITIAL VECTOR VALUED PROBLEM
C ITERATION SCHEME IS BASED ON ON A QUASI-NEWTON
C METHOD IN AN 1984 IMSL SUBROUTINE.
C REFERENCE IS THE MINIPACK PACKAGE
C  BASED ON POWELL'S HYBRID ALGORITHM WHICH USES A FINITE DIFFERENCE
C APPROX. TO THE JACOBIAN AND TAKES PERCAUTIONS TO AVOID LARGE STEP SIZES
C OR INCREASING RESIDUALS
C X(*)=INITIAL STARTING VECTOR FOR QUASI NEWTON METHOD
C THE CLOSER THE GUESS,THE FASTER IT CONVERGES.
         N=2
         X(1)=1.5*Y(1)
         X(2)=1.5*Y(2)
        PAR(1)=Y(1)
       PAR(2)=Y(2)
            PAR(3)=H
          NSIG=3
            ITMAX=200
c           write(6,*)tau(1),tau(2),Y(1),Y(2),h
          CALL ZSPOW(FCN,NSIG,N,ITMAX,PAR,X,FNORM,WK,IER)
       IF(IER .EQ. 131)then
!        write(27,*)X(1),X(2),Y(1),Y(2),taur,h,xmhigh
        stop
        endif
      DO 10 I=1,N
       Y(I)=X(I)
10     CONTINUE
c     write(6,*)Y(1),Y(2)
!               WRITE(27,22)
22          FORMAT('IMPLICIT SCHEME')
            RETURN
            END
