      SUBROUTINE M2ODEINT(YSTART,NVAR,X1,X2,EPS,H1,HMIN,NOK,NBAD,DERIVS,
     1RKQC)
      PARAMETER (MAXSTP=100,NMAX=2,TWO=2.0,ZERO=0.00,TINY=1.0E-30)
       COMMON /PATH/KMAX,KOUNT,DXSAV,XP(200),YP(10,200)
       DIMENSION YSTART(NVAR),YSCAL(NMAX),Y(NMAX),DYDX(NMAX)
           EXTERNAL DERIVS
       X=X1
       H=sign(H1,X2-X1)
         NOK=0
         NBAD=0
         KMAX=0
       DO 11 I=1,NVAR
        Y(I)=YSTART(I)
11     CONTINUE
C  ASSURE STORAGE OF FIRST STEP
           XSAV=X-DXSAV*TWO
C     TAKE AT MOST MAXSTP STEPS
       DO 16 NSTP=1,MAXSTP
       CALL m2derivs(X,Y,DYDX)
       DO 12 I=1,NVAR
C  SCALING USED TO MONITOR ACCURACY. THIS CAN BE MODIFIED AS NEEDED
       YSCAL(I)=abs(Y(I))+abs(H*DYDX(I))+TINY
12     CONTINUE
        IF((X+H-X2)*(X+H-X1) .GT. ZERO)H=X2-X
C IF STEP CAN OVERSHOOT END,CUT DOWN STEPSIZE
      CALL M2RKQC(Y,DYDX,NVAR,X,H,EPS,YSCAL,HDID,HNEXT,DERIVS,HMIN)
ck         WRITE(27,22)Y(1),Y(2),X
ck22        FORMAT(5x,'TAU1=',e15.8,2x,'TAU2=',e15.8,2x,'dt=',f8.5/)
         IF((X-X2)*(X2-X1) .GE. ZERO)THEN
C ARE WE DONE?
         DO 14 I=1,NVAR
           YSTART(I)=Y(I)
14        CONTINUE
          RETURN
          ENDIF
16       CONTINUE
        IF(abs(HNEXT) .LT. HMIN)H=HNEXT
        WRITE(27,31)
31      FORMAT(' STEPSIZE SMALLER THAN MINIMUM')
         RETURN
         END

